### ISSUE TITLE
How to pass data arguments? and headers?

### ISSUE THREAD

**Issue by gkorland** [wei/curl#10]
I'm getting a YAML error on the following:
```
    - name: verify with curl
      uses: wei/curl@v1.1.1
      with:
        args: http://localhost:5000/chat -H "Content-Type: application/json" -d '{"message": "I am crazy"}'
```
