### ISSUE TITLE
retry arguments are ignored

### ISSUE THREAD

**Issue by gkorland** [wei/curl#11]
```
    - name: Verify with curl
      uses: wei/curl@v1.1.1
      with:
        args: http://localhost:5000/chat --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -H "Content-Type:application/json" -d '{"message":"I am crazy"}'
```

I still get this error:
```
curl: (7) Failed to connect to localhost port 5000 after 0 ms: Connection refused
```
