### ISSUE TITLE
Downloads are empty

### ISSUE THREAD

**Issue by makinox** [wei/curl#8]
I'm trying this code
```yml
- name: Download backup archives
  uses: wei/curl@v1.1.1
  with:
    args: ${{ secrets.ARCHIVE_BACKUP }} -O
```
Download an empty file
`
-rw-r--r--    1 root   root      0 Jul 14 15:13 archiveDocsBackup.tar.gz
`
So I don't know what I'm doing wrong.
